### PR TITLE
Reuse same env var as sonar collector docker properties builder

### PR DESCRIPTION
**Pull request by yannschepens**
In order to normalize env var for collectors.
And remove useless MONGO_PORT env var, this not consistent and useless (my opinion)

### CODE REVIEW

**Review by rvema — DISMISSED** [review]
lgtm, please sign the CLA so that this change can be merged

**Comment by rvema** [comment]
@yannschepens please sign the CLA so that this change can be accepted

**Comment by yannschepens** [comment]
Damn I did an error, wait a second

**Comment by rvema** [comment]
> Damn I did an error, wait a second

sure, let me know when you are ready

**Comment by yannschepens** [comment]
I gonna close this one (I tried to change the commiter, but unfortunatelly it changes more things that I though)

**Comment by yannschepens** [comment]
I can't sign the CLA with my professional mail address. Sorry

You can go to this one : https://github.com/Hygieia/hygieia-scm-gitlab-collector/pull/23 with my personal one.

**Pull request closed without merging**
